<?php

use App\Http\Controllers\AddressController;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\ChatController;
use App\Http\Controllers\DeliveryController;
use App\Http\Controllers\DisputeController;
use App\Http\Controllers\KycController;
use App\Http\Controllers\MeController;
use App\Http\Controllers\MediaController;
use App\Http\Controllers\OperationsController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\ReviewController;
use App\Http\Controllers\SupportController;
use Illuminate\Support\Facades\Route;

// Memes chemins que server/app/routers/auth.py (et ApiEndpoints.dart cote
// mobile) : aucun changement d'URL entre les deux backends.
Route::prefix('auth')->group(function () {
    Route::post('/otp/request', [AuthController::class, 'requestOtp'])->middleware('throttle:auth-code');
    Route::post('/otp/verify', [AuthController::class, 'verifyOtp'])->middleware('throttle:auth-login');
    Route::post('/phone/login', [AuthController::class, 'phoneLogin'])->middleware('throttle:auth-login');
    Route::post('/phone/register', [AuthController::class, 'phoneRegister'])->middleware('throttle:auth-public');
    Route::post('/devices', [AuthController::class, 'enrollDevice']);

    Route::post('/email/request', [AuthController::class, 'requestEmailCode'])->middleware('throttle:auth-code');
    Route::post('/email/verify', [AuthController::class, 'verifyEmailCode'])->middleware('throttle:auth-login');
    Route::post('/email/register', [AuthController::class, 'registerWithEmail'])->middleware('throttle:auth-public');
    Route::post('/password/signin', [AuthController::class, 'signInWithPassword'])->middleware('throttle:auth-login');
    Route::post('/password/signup', [AuthController::class, 'signUpWithPassword'])->middleware('throttle:auth-public');
    Route::post('/password/reset', [AuthController::class, 'resetPassword'])->middleware('throttle:auth-login');
    Route::post('/email/change/request', [AuthController::class, 'requestEmailChange'])->middleware('throttle:auth-code');
    Route::post('/email/change/verify', [AuthController::class, 'verifyEmailChange']);
    Route::post('/phone/change/request', [AuthController::class, 'requestPhoneChange'])->middleware('throttle:auth-code');
    Route::post('/phone/change/verify', [AuthController::class, 'verifyPhoneChange']);
    Route::post('/email/link', [AuthController::class, 'linkEmail']);
    Route::post('/password/change', [AuthController::class, 'changePassword'])->middleware('throttle:auth-login');
    Route::get('/sessions', [AuthController::class, 'sessions']);
    Route::delete('/sessions/{family}', [AuthController::class, 'revokeSession']);

    Route::post('/refresh', [AuthController::class, 'refresh'])->middleware('throttle:auth-public');
    Route::post('/logout', [AuthController::class, 'logout']);
});

Route::get('/me', [MeController::class, 'show']);
Route::patch('/me', [MeController::class, 'update']);
Route::post('/me/avatar', [MeController::class, 'uploadAvatar']);
Route::delete('/me/avatar', [MeController::class, 'deleteAvatar']);
Route::get('/accounts/{accountId}/avatar', [MeController::class, 'readAvatar']);

Route::prefix('addresses')->group(function () {
    Route::get('', [AddressController::class, 'index']);
    Route::post('', [AddressController::class, 'store']);
    Route::patch('/{addressId}', [AddressController::class, 'update']);
    Route::delete('/{addressId}', [AddressController::class, 'destroy']);
});

Route::post('/media', [MediaController::class, 'store']);
Route::get('/media/{mediaId}', [MediaController::class, 'show']);
Route::post('/uploads', [MediaController::class, 'store']);
Route::get('/uploads/{mediaId}', [MediaController::class, 'show']);
Route::get('/drivers/kyc/status', [KycController::class, 'status']);
Route::get('/drivers/kyc/messages', [KycController::class, 'messages']);
Route::post('/drivers/kyc/messages', [KycController::class, 'sendMessage']);
Route::post('/drivers/kyc/documents/{kind}', [KycController::class, 'upload']);
Route::delete('/drivers/kyc/documents/{kind}', [KycController::class, 'delete']);
Route::post('/drivers/kyc', [KycController::class, 'submit']);
Route::get('/accounts/{accountId}/kyc/{kind}', [KycController::class, 'read']);
Route::post('/reviews', [ReviewController::class, 'store']);
Route::get('/reviews/delivery/{deliveryId}', [ReviewController::class, 'show']);
Route::get('/notifications', [SupportController::class, 'notifications']);
Route::post('/notifications/{notificationId}/read', [SupportController::class, 'markNotificationRead']);
Route::delete('/notifications/{notificationId}', [SupportController::class, 'deleteNotification']);
Route::post('/contact', [SupportController::class, 'contact'])->middleware('throttle:public-track');
Route::get('/contact', [SupportController::class, 'contacts']);
Route::get('/admin/contact', [SupportController::class, 'adminContacts']);
Route::post('/admin/contact/{messageId}/reply', [SupportController::class, 'replyContact']);
Route::get('/admin/dashboard', [AdminController::class, 'dashboard']);
Route::get('/admin/stats', [AdminController::class, 'dashboard']);
Route::get('/admin/reports/deliveries.csv', [AdminController::class, 'exportDeliveries']);
Route::get('/admin/fleet', [AdminController::class, 'fleet']);
Route::get('/admin/users', [AdminController::class, 'users']);
Route::post('/admin/drivers/{driverId}/suspension', [AdminController::class, 'suspendDriver']);
Route::post('/admin/users/{accountId}/suspension', [AdminController::class, 'suspendUser']);
Route::get('/admin/moderation', [AdminController::class, 'moderation']);
Route::get('/admin/system/audit', [SupportController::class, 'audit']);
Route::get('/admin/settings', [SupportController::class, 'settings']);
Route::put('/admin/settings/{key}', [SupportController::class, 'updateSetting']);
Route::get('/disputes/{disputeId}/files', [SupportController::class, 'files']);
Route::post('/disputes/{disputeId}/files', [SupportController::class, 'addFile']);
Route::prefix('payments')->group(function () {
    Route::get('/balance', [PaymentController::class, 'balance']);
    Route::get('/history', [PaymentController::class, 'history']);
    Route::post('/intent', [PaymentController::class, 'createIntent']);
    Route::get('/{paymentId}', [PaymentController::class, 'show']);
    Route::post('/{paymentId}/claim', [PaymentController::class, 'claim']);
    Route::post('/{paymentId}/confirm', [PaymentController::class, 'confirm']);
    Route::post('/{paymentId}/cash', [PaymentController::class, 'cash']);
    Route::post('/withdraw', [PaymentController::class, 'withdraw']);
});
Route::get('/disputes', [DisputeController::class, 'index']);
Route::post('/disputes', [DisputeController::class, 'store']);
Route::get('/disputes/{disputeId}', [DisputeController::class, 'show']);
Route::post('/disputes/{disputeId}/messages', [DisputeController::class, 'message']);
Route::post('/disputes/{disputeId}/decision', [DisputeController::class, 'decision']);
Route::get('/conversations', [ChatController::class, 'conversations']);
Route::post('/conversations/admin', [ChatController::class, 'startAdminConversation']);
Route::get('/conversations/search', [ChatController::class, 'search']);
Route::post('/conversations/{conversationId}/archive', [ChatController::class, 'archive']);
Route::post('/conversations/{conversationId}/restore', [ChatController::class, 'restore']);
Route::post('/conversations/{conversationId}/block', [ChatController::class, 'block']);
Route::post('/conversations/{conversationId}/unblock', [ChatController::class, 'unblock']);
Route::delete('/conversations/{conversationId}', [ChatController::class, 'deleteConversation']);
Route::get('/conversations/{conversationId}/messages', [ChatController::class, 'conversationMessages']);
Route::post('/conversations/{conversationId}/messages', [ChatController::class, 'sendConversationMessage']);
Route::get('/deliveries/{deliveryId}/messages', [ChatController::class, 'messages']);
Route::post('/deliveries/{deliveryId}/messages', [ChatController::class, 'send']);
Route::post('/deliveries/{deliveryId}/messages/read', [ChatController::class, 'markRead']);
Route::get('/kyc', [KycController::class, 'queue']);
Route::get('/admin/kyc', [KycController::class, 'queue']);
Route::get('/kyc/{driverId}/documents', [KycController::class, 'adminDocuments']);
Route::get('/kyc/{driverId}/messages', [KycController::class, 'adminMessages']);
Route::post('/kyc/{driverId}/messages', [KycController::class, 'adminSendMessage']);
Route::post('/kyc/{driverId}/review', [KycController::class, 'review']);
Route::get('/admin/kyc/{driverId}/documents', [KycController::class, 'adminDocuments']);
Route::get('/admin/kyc/{driverId}/messages', [KycController::class, 'adminMessages']);
Route::post('/admin/kyc/{driverId}/messages', [KycController::class, 'adminSendMessage']);
Route::post('/admin/kyc/{driverId}/review', [KycController::class, 'review']);
Route::get('/relay-points', [DeliveryController::class, 'relayPoints']);
Route::get('/track/{token}', [DeliveryController::class, 'track'])->middleware('throttle:public-track');
Route::get('/public/track/{token}', [DeliveryController::class, 'track'])->middleware('throttle:public-track');
Route::get('/deliveries/available', [DeliveryController::class, 'available']);
Route::post('/driver/status', [DeliveryController::class, 'driverStatus']);
Route::get('/driver/vehicle', [DeliveryController::class, 'vehicle']);
Route::patch('/driver/vehicle', [DeliveryController::class, 'updateVehicle']);
Route::post('/tracking/batch', [DeliveryController::class, 'trackingBatch']);
Route::post('/drivers/emergency', [OperationsController::class, 'raiseEmergency']);
Route::get('/drivers/emergency', [OperationsController::class, 'emergencies']);
Route::post('/admin/emergencies/{alertId}/acknowledge', [OperationsController::class, 'acknowledgeEmergency']);
Route::post('/admin/deliveries/{id}/reassign', [OperationsController::class, 'reassign']);
Route::prefix('deliveries')->group(function () {
    Route::get('', [DeliveryController::class, 'index']);
    Route::post('', [DeliveryController::class, 'store']);
    Route::get('/{id}', [DeliveryController::class, 'show']);
    Route::post('/{id}/cancel', [DeliveryController::class, 'cancel']);
    Route::post('/{id}/accept', [DeliveryController::class, 'accept']);
    Route::post('/{id}/status', [DeliveryController::class, 'status']);
    Route::post('/{id}/incidents', [DeliveryController::class, 'reportIncident']);
    Route::get('/{id}/incidents', [DeliveryController::class, 'incidents']);
    Route::get('/{id}/trace', [OperationsController::class, 'trace']);
    Route::get('/{id}/custody', [OperationsController::class, 'custody']);
    Route::post('/{id}/custody/pickup', [OperationsController::class, 'custodyPickup']);
    Route::post('/{id}/custody/handover', [OperationsController::class, 'custodyHandover']);
});
